### ISSUE TITLE
Windows 2012 Support

### ISSUE THREAD

**Issue by dmikalova** [opscode-cookbooks/windows#109]
Windows 2012 isn't documented as being supported, for example in the readme.

**Comment by spuder** [comment]
This is a good question, has anyone found out for sure if this works with 2012?

**Comment by AnneTheAgile** [comment]
win8 surfpro3 here, I could check out at least parts, but I'm a chef newbie.

>Therefore the recipe would work if you just use Windows 8 as the platform

How do I change the platform? ty! AnneTheAgile

**Comment by lolindirfalasion** [comment]
I've been successful with it on Windows Server 2012 and R2.  Haven't seen a use to using it on a Surface Pro.

**Comment by forehand** [comment]
I've used batch, dism, powershell and registry with 2012 r2 without issue.  Having trouble with the reboot handler but I think that's just me.

**Comment by rlaveycal** [comment]
reboot handler works fine for me on 2012 R2
