### ISSUE TITLE
windows_package fails to install MSI with error 1603

### ISSUE THREAD

**Issue by ericlathrop** [opscode-cookbooks/windows#130]
This is probably the same problem that caused https://github.com/opscode/knife-windows/issues/96 and probably needs whatever fix they used.

Here's a snip from my logfile:
```
windows_package("Applicaton Request Routing 3.0") do
  action [:install]
  retries 0
  retry_delay 2
  guard_interpreter :default
  cookbook_name "imagekind_windows"
  recipe_name "iis_arr"
  source "http://download.microsoft.com/download/6/3/D/63D67918-483E-4507-939D-7F8C077F889E/requestRouter_x64.msi"
  package_name "Applicaton Request Routing 3.0"
  timeout 600
  success_codes [0, 42, 127]
end

[2014-10-15T18:40:53+00:00] INFO: Running queued delayed notifications before re-raising exception
[2014-10-15T18:40:53+00:00] ERROR: Running exception handlers
[2014-10-15T18:40:53+00:00] ERROR: Exception handlers complete
[2014-10-15T18:40:53+00:00] FATAL: Stacktrace dumped to c:/chef/cache/chef-stacktrace.out
[2014-10-15T18:40:53+00:00] FATAL: Mixlib::ShellOut::ShellCommandFailed: windows_package[Applicaton Request Routing 3.0] (imagekind_windows::iis_arr line 12) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0, 42, 127], but received '1603'
```
From what I can tell Microsoft put out a security patch that breaks installing programs remotely, unless you've logged into a graphical session.

**Comment by codesilverback** [comment]
Did you ever resolve this?  I'm seeing the same thing with Splunk forwarder installs on Win 2012 cloud boxes at Rackspace.

**Comment by ericlathrop** [comment]
@codesilverback Nope, I ended up shedding most of my Chef infastructure and pre-baking my AMI's.

**Comment by codesilverback** [comment]
That's what I was afraid of.  The chef bootstrapper uses a workaround of creating a scheduled task to run the installer, and that seems to work, but wow.  What a hack!

**Comment by adamedx** [comment]
@codesilverback, do you know if those win2k12 systems are fully patched? If not, they could be hitting the original problem that was broken by the Windows patch. If the installation of the chef-client msi works fine when you log on interactively, but fails remotely if you've never logged in to the system, that would suggest the same problem.

**Comment by Tech356** [comment]
Have you tired rebooting before installing the app that throws the 1603 error? I have a couple apps that throw that code. I just have to make sure nothing else installed before it. 

My hunch is that it has something to do with some pending operations (like [PendingFileRenameOperations](https://technet.microsoft.com/en-us/library/cc960241.aspx)) but I haven't investigated it too deeply.
