### ISSUE TITLE
windows_reboot resource does not execute if timeout is not specified and the name of the resource is a string

### ISSUE THREAD

**Issue by arthurgreef** [opscode-cookbooks/windows#139]
This does not result in a reboot.

windows_reboot "anything" do
    reason 'Reboot'
    action :request
    only_if { reboot_pending? }
end

This does result in a reboot

windows_reboot "something" do
    timeout 1
    reason 'Reboot'
    action :request
    only_if { reboot_pending? }
end

**Comment by ksubrama** [comment]
I think the name_attribute issue is https://tickets.opscode.com/browse/CHEF-4262.  Let me see if we have a newer ticket somewhere.  I can fix the issue with a blank reason by giving it a better default in the resource.
