### ISSUE TITLE
windows_task does not delete task

### ISSUE THREAD

**Issue by tsgood77** [opscode-cookbooks/windows#165]
I have tried the following on one of our cloud VM's and also on a local Vagrant Windows 2008R2 test VM.

I create a scheduled task pretty much using your sample code:

windows_task 'Chef client' do
  user 'Administrator'
  password '*********'
  cwd 'C:\chef\bin'
  command 'chef-client -L C:\\tmp\\'
  run_level :highest
  frequency :minute
  frequency_modifier 15
end

I confirm that the task is there.  I then run only the following:

windows_task 'Chef client' do
  action :delete
end

Logging reports the task has successfully been deleted.  It has not.

I am getting around this at the moment by using the batch resource to run SchTasks  with the /F to silently delete the task.

**Comment by kenny-evitt** [comment]
I also have observed this issue for two computers, one running Windows 7 and the second running Windows Server 2008.

**Comment by jdmundrawala** [comment]
Yea, schtasks.exe is bringing up a prompt, and it defaults to not deleting the task. This resource is useless without using `force true`
cc @smurawski @btm

**Comment by jdmundrawala** [comment]
@smurawski is there any reason not to force delete?

**Comment by smurawski** [comment]
@jdmundrawala Nope, if we've defined the action as delete, it should delete.

**Comment by smurawski** [comment]
Closed via #204
