### ISSUE TITLE
Undefined method "compile_time" Chef 12.0.3

### ISSUE THREAD

**Issue by swade1987** [opscode-cookbooks/windows#181]
I am trying to run a Berkshelf cookbook which requires the windows cookbook to be ran first.

However when it runs the follow error is displayed

Undefined method "compile_time"

Note I am running this on a Windows Server 2012 R2 box.

Any ideas?

**Comment by docwhat** [comment]
This appears to be only in v1.36.2

v1.36.1 works fine.

**Comment by docwhat** [comment]
This seems to be fixed in 5f2e6ff665c4122bb5222bb5cebc23f387eeb612 (which is/will-be in v1.36.3)

**Comment by btm** [comment]
1.36.3 shipped on 2014-12-18, and there's been a couple releases since then as well, so I presume this is fixed/working fine now based on @docwhat's comments . Please let me know if that's not true.
