### ISSUE TITLE
Upgrading Windows cookbook causes windows_package resource failure installing PowerShell4

### ISSUE THREAD

**Issue by sneal** [opscode-cookbooks/windows#183]
I upgraded the Windows cookbook from 1.31.2 to 1.36.6, without changing _anything_ else and now the powershell::powershell4 recipe is failing. Downgrading the Windows cookbook to the old version and re-running succeeds, so something in the Windows cookbook has changed that the PowerShell cookbook doesn't like.

- Windows Server 2008 R2 SP1 fully patched
- NET 4.5.2
- Chef 11.12.4

Here's the output:
```
[2015-02-19T16:08:53-08:00] INFO: Processing remote_file[c:/chef/cache/Windows6.1-KB2819745-x64-MultiPkg.msu] action create (dynamically defined)
[2015-02-19T16:08:54-08:00] INFO: Starting installation...this could take awhile.

================================================================================
Error executing action `install` on resource 'windows_package[Windows Management Framework Core4.0]'
================================================================================

Mixlib::ShellOut::ShellCommandFailed
------------------------------------
Expected process to exit with [0, 42, 127, 3010], but received '2359302'
---- Begin output of start "" /wait "c:\chef\cache\Windows6.1-KB2819745-x64-MultiPkg.msu" /quiet /norestart & exit %%ERRORLEVEL%% ----
STDOUT: 
STDERR: 
---- End output of start "" /wait "c:\chef\cache\Windows6.1-KB2819745-x64-MultiPkg.msu" /quiet /norestart & exit %%ERRORLEVEL%% ----
Ran start "" /wait "c:\chef\cache\Windows6.1-KB2819745-x64-MultiPkg.msu" /quiet /norestart & exit %%ERRORLEVEL%% returned 2359302

Cookbook Trace:
---------------
c:/chef/cache/cookbooks/windows/libraries/windows_package.rb:109:in `install_package'
c:/chef/cache/cookbooks/windows/libraries/windows_package.rb:31:in `block in <class:WindowsCookbookPackage>'

Resource Declaration:
---------------------
# In c:/chef/cache/cookbooks/powershell/recipes/powershell4.rb

 36:     windows_package 'Windows Management Framework Core4.0' do
 37:       source node['powershell']['powershell4']['url']
 38:       checksum node['powershell']['powershell4']['checksum']
 39:       installer_type :custom
 40:       options '/quiet /norestart'
 41:       action :install
 42:       success_codes [0, 42, 127, 3010]
 43:       # Note that the :immediately is to immediately notify the other resource,
 44:       # not to immediately reboot. The windows_reboot 'notifies' does that.
 45:       notifies :request, 'windows_reboot[powershell]', :immediately if reboot_pending? && node['powershell']['installation_reboot_mode'] != 'no_reboot'
 46:       not_if do
 47:         begin
 48:           registry_data_exists?('HKLM\SOFTWARE\Microsoft\PowerShell\3\PowerShellEngine', { :name => 'PowerShellVersion', :type => :string, :data => '4.0' })
 49:         rescue Chef::Exceptions::Win32RegKeyMissing
 50:           false
 51:         end
 52:       end
 53:     end
 54:   else

Compiled Resource:
------------------
# Declared in c:/chef/cache/cookbooks/powershell/recipes/powershell4.rb:36:in `from_file'

windows_cookbook_package("Windows Management Framework Core4.0") do
  provider Chef::Provider::WindowsCookbookPackage
  action [:install]
  retries 0
  retry_delay 2
  guard_interpreter :default
  cookbook_name "powershell"
  recipe_name "powershell4"
  source "http://download.microsoft.com/download/3/D/6/3D61D262-8549-4769-A660-230B67E15B25/Windows6.1-KB2819745-x64-MultiPkg.msu"
  checksum "fbc0889528656a3bc096f27434249f94cba12e413142aa38946fcdd8edf6f4c5"
  installer_type :custom
  options "/quiet /norestart"
  timeout 600
  success_codes [0, 42, 127, 3010]
  package_name "Windows Management Framework Core4.0"
  not_if { #code block }
end

```

**Comment by jdmundrawala** [comment]
@sneal is it possible that the update is already installed?
Also, anything interesting in the eventlog?

**Comment by sneal** [comment]
Its already installed, so it would seem to be a problem with the way idempotence is handled.

**Comment by jdmundrawala** [comment]
it's possible the guard is not working: https://github.com/opscode-cookbooks/powershell/blob/master/recipes/powershell4.rb#L48

**Comment by sneal** [comment]
That's possible, I'll look into that. Its odd though, why would upgrading the Windows cookbook cause this? It looks like the package resource has been removed, so does that mean by upgrading I'm not using the core Chef package resource anymore? If so, it seems the issue isn't a Windows cookbook issue. Its either the core package provider and/or the PS cookbook.

**Comment by jdmundrawala** [comment]
the package resource has not been removed, just had to move it. https://github.com/opscode-cookbooks/windows/blob/master/libraries/windows_package.rb

It's very curious why it would work with an older version of the windows cookbook and not the newer one.  It's possible that switching from the pure LWRP file to inheriting from the LWRP class is doing something weird with guards.

**Comment by jdmundrawala** [comment]
We can narrow that down a little bit... version 1.34.8 still uses the lwrp for windows package

**Comment by jdmundrawala** [comment]
With Chef 11.16.4 and windows cookbook master,
```ruby
windows_package 'Mozilla Firefox 5.0 (x86 en-US)' do
  source 'http://archive.mozilla.org/pub/mozilla.org/mozilla.org/firefox/releases/5.0/win32/en-US/Firefox%20Setup%205.0.exe'
  options '-ms'
  installer_type :custom
  action :install
  not_if { true }
end
```
works as expected

I'm going to try chef 11.12.4

**Comment by sneal** [comment]
The 1.34.8 Windows cookbook version works fine.

```
INFO: Processing windows_package[Windows Management Framework Core4.0] action install (powershell::powershell4 line 36)
INFO: Installing windows_package[Windows Management Framework Core4.0] version latest
INFO: Processing remote_file[c:/chef/cache/Windows6.1-KB2819745-x64-MultiPkg.msu] action create (dynamically defined)
INFO: Starting installation...this could take awhile.
```

The entire reason I went down this road was to upgrade to the latest Chef 11.x release, but found I needed to upgrade the Windows cookbook because of some wmi gem error. I wanted to make sure upgrading the Windows cookbook wouldn't break all our existing Chef 11.12.4 installs.

**Comment by jdmundrawala** [comment]
It looks like it is reinstalling? It should have skipped the resource, right?

**Comment by sneal** [comment]
You're right, I don't see that on my box with Chef 11.18.6. I'm going to reboot my 11.12.4 box, I noticed PowerShell4 is completely installed until after a reboot.

**Comment by sneal** [comment]
Once I rebooted the box, using the latest version of the Windows cookbook does in fact work, so I'm going to close this issue. It seems the new windows_package implementation is correct, it doesn't swallow errors like the old one.

**Comment by jdmundrawala** [comment]
@sneal is there still a bug in the powershell cookbook?
https://github.com/opscode-cookbooks/powershell/issues/40

**Comment by sneal** [comment]
@jdmundrawala Maybe. Querying the PowerShell version returned 2 until I rebooted the node, at which point it started to return 4. The problem is that PowerShell doesn't finish installing until reboot so its only a problem if you run Chef twice in a row without rebooting.

I'd prefer the PowerShell4 recipe didn't error out on the second converge, but the guard clause is technically correct. /CC @juliandunn
