### ISSUE TITLE
box urls in kitchen.yml out of date 

### ISSUE THREAD

**Issue by irabinovitch** [opscode-cookbooks/windows#188]
The box_urls for images in .kitchen.yml (https://github.com/opscode-cookbooks/windows/blob/master/.kitchen.yml) look to be outdated urls.

eg:
http://cdn.box-cutter.com/windows/virtualbox4.3.20/eval-win81x64-enterprise-nocm-1.0.2.box

**Comment by btm** [comment]
We're working with Microsoft to try to find a way to distribute Windows images.
