### ISSUE TITLE
Installing some windows features fail over winrm on Server 2012

### ISSUE THREAD

**Issue by tophercullen** [opscode-cookbooks/windows#196]
Most the time, installing features remotely using dism works fine. However, I ran into an issue when trying to install ASP.Net 3 ( aka DISM "NetFx3"). Running chef-client locally has no issues
It can be reproduced with either chef remotely or running the commands directly over winrm
 ```ruby 
features = %w{NetFx3ServerFeatures NetFx3}
features.each do |feature|
  windows_feature feature do
    action :install
  end
end
```
The first feature installs correctly, the second does not. 
The remote command it ends up calling is:
```dos
C:\Windows\System32\dism.exe /online /enable-feature /featurename:NetFx3 /norestart
```
Which fails with error "The source files could not be downloaded."
Digging around int he logs show:
C:\Windows\Logs\DISM\dism.log:
  Encountered an unknown option "featurename" with value "NetFx3"
C:\Windows\Logs\CBS\CBS.log : 
CBS    Failed to create downloader [HRESULT = 0x80070005 - E_ACCESSDENIED]
Based upon the source links provided at the end, it seems that this method is not allowed remotely and there is no way to change that. Why its being invoked for one package and not another is beyond me.

The workaround I have now, is to not use winrm or instead call powershell remotely
knife winrm 'name:<mymachine>' 'powershell.exe -Command Install-WindowsFeature NET-Framework-Core'

Sources:
http://lists.opscode.com/sympa/arc/chef/2013-05/msg00513.html
https://msdn.microsoft.com/en-us/library/aa387288(VS.85).aspx
https://msdn.microsoft.com/en-us/library/aa386862(v=vs.85).aspx

**Comment by lolindirfalasion** [comment]
Our experience is that netfx3 needs the alternative source option on server 2012 as the source files are not provided during install, but are available on the installation media

**Comment by tophercullen** [comment]
I forgot to note that running chef-client locally works perfectly fine. This only applies when running chef-client remotely

**Comment by smurawski** [comment]
This is due to the .NET 3.5 feature not being included in the base image.  It is on the install media (in Sources/sxs).  In order to install that feature (or any feature not included in the installed image), you have to use the source attribute and point to a location where the SYSTEM account has access.  

When run from an interactive login session, DISM or Add-WindowsFeature can use Windows Update to get the .NET bits, but that API does not work from a non-interactive context (e.g. from winrm).

**Comment by smurawski** [comment]
There is actually an example of this in the readme - https://github.com/opscode-cookbooks/windows#examples-2
