### ISSUE TITLE
Windows 1.37.0 with PR#204 is breaking existing cookbooks using windows_task resource

### ISSUE THREAD

**Issue by ebrahim-moshaya** [opscode-cookbooks/windows#219]
Unfortunately, Pull Request#204 breaks all of our existing internal cookbooks with the windows_task resource using this new pr as well as chef-client::task...

https://github.com/opscode-cookbooks/chef-client/issues/313

**Comment by jdmundrawala** [comment]
I think I know what the problem is, but I need you to post the stack trace to be sure. Also, the user you are trying to set would be useful

**Comment by ebrahim-moshaya** [comment]
Error executing action create on resource 'windows_task[\chef-client]'
================================================================================

NoMethodError

undefined method `password=' for Chef::Resource::WindowsTask

Resource Declaration:

# In C:/tmp/kitchen/cache/cookbooks/chef-client/recipes/task.rb

32: windows_task 'chef-client' do
33: run_level :highest
34: command "cmd /c '#{node['chef_client']['ruby_bin']} #{node['chef_client']['bin']} \
35: -L #{File.join(node['chef_client']['log_dir'], 'client.log')} \
36: -c #{File.join(node['chef_client']['conf_dir'], 'client.rb')} -s #{node['chef_client']['splay']} > NUL 2>&1'"
37:
38: user node['chef_client']['task']['user']
39: password node['chef_client']['task']['password']
40: frequency node['chef_client']['task']['frequency'].to_sym
41: frequency_modifier node['chef_client']['task']['frequency_modifier']
42: start_time node['chef_client']['task']['start_time'] || start_time
43: end

Compiled Resource:

# Declared in C:/tmp/kitchen/cache/cookbooks/chef-client/recipes/task.rb:32:in `from_file'

windows_task("\chef-client") do
action :create
retries 0
retry_delay 2
default_guard_interpreter :default
declared_type :windows_task
cookbook_name "chef-client"
recipe_name "task"
run_level :highest
command "cmd /c ' C:/opscode/chef/bin/chef-client -L C:/chef/log/client.log -c C:/chef/client.rb -s 300 > NUL 2>&1'"
user "SYSTEM"
frequency :onstart
frequency_modifier 30
task_name "\chef-client"
end

**Comment by jdmundrawala** [comment]
there should also be a chef-stacktrace.out file somewhere that contains the stacktrace

**Comment by ebrahim-moshaya** [comment]
[2015-05-27T14:48:54.579063 #13812]  INFO -- packager-Windows2012: Recipe: chef-client::task
I, [2015-05-27T14:48:54.593566 #13812]  INFO -- packager-Windows2012: 
I, [2015-05-27T14:48:54.597067 #13812]  INFO -- packager-Windows2012:     
I, [2015-05-27T14:48:54.597567 #13812]  INFO -- packager-Windows2012:     ================================================================================
I, [2015-05-27T14:48:54.597567 #13812]  INFO -- packager-Windows2012:     Error executing action `create` on resource 'windows_task[\chef-client]'
I, [2015-05-27T14:48:54.597567 #13812]  INFO -- packager-Windows2012:     ================================================================================
I, [2015-05-27T14:48:54.597567 #13812]  INFO -- packager-Windows2012:     
I, [2015-05-27T14:48:54.598067 #13812]  INFO -- packager-Windows2012:     NoMethodError
I, [2015-05-27T14:48:54.598067 #13812]  INFO -- packager-Windows2012:     -------------
I, [2015-05-27T14:48:54.598067 #13812]  INFO -- packager-Windows2012:     undefined method `password=' for Chef::Resource::WindowsTask
I, [2015-05-27T14:48:54.598067 #13812]  INFO -- packager-Windows2012:     
I, [2015-05-27T14:48:54.598067 #13812]  INFO -- packager-Windows2012:     Resource Declaration:
I, [2015-05-27T14:48:54.598067 #13812]  INFO -- packager-Windows2012:     ---------------------
I, [2015-05-27T14:48:54.598567 #13812]  INFO -- packager-Windows2012:     # In C:/tmp/kitchen/cache/cookbooks/chef-client/recipes/task.rb
I, [2015-05-27T14:48:54.598567 #13812]  INFO -- packager-Windows2012:     
I, [2015-05-27T14:48:54.598567 #13812]  INFO -- packager-Windows2012:      32: windows_task 'chef-client' do
I, [2015-05-27T14:48:54.598567 #13812]  INFO -- packager-Windows2012:      33:   run_level :highest
I, [2015-05-27T14:48:54.598567 #13812]  INFO -- packager-Windows2012:      34:   command "cmd /c '#{node['chef_client']['ruby_bin']} #{node['chef_client']['bin']} \
I, [2015-05-27T14:48:54.598567 #13812]  INFO -- packager-Windows2012:      35:   -L #{File.join(node['chef_client']['log_dir'], 'client.log')} \
I, [2015-05-27T14:48:54.598567 #13812]  INFO -- packager-Windows2012:      36:   -c #{File.join(node['chef_client']['conf_dir'], 'client.rb')} -s #{node['chef_client']['splay']} > NUL 2>&1'"
I, [2015-05-27T14:48:54.598567 #13812]  INFO -- packager-Windows2012:      37: 
I, [2015-05-27T14:48:54.599067 #13812]  INFO -- packager-Windows2012:      38:   user               node['chef_client']['task']['user']
I, [2015-05-27T14:48:54.599067 #13812]  INFO -- packager-Windows2012:      39:   password           node['chef_client']['task']['password']
I, [2015-05-27T14:48:54.599067 #13812]  INFO -- packager-Windows2012:      40:   frequency          node['chef_client']['task']['frequency'].to_sym
I, [2015-05-27T14:48:54.599067 #13812]  INFO -- packager-Windows2012:      41:   frequency_modifier node['chef_client']['task']['frequency_modifier']
I, [2015-05-27T14:48:54.599067 #13812]  INFO -- packager-Windows2012:      42:   start_time         node['chef_client']['task']['start_time'] || start_time
I, [2015-05-27T14:48:54.599067 #13812]  INFO -- packager-Windows2012:      43: end
I, [2015-05-27T14:48:54.599067 #13812]  INFO -- packager-Windows2012:     
I, [2015-05-27T14:48:54.599067 #13812]  INFO -- packager-Windows2012:     Compiled Resource:
I, [2015-05-27T14:48:54.599567 #13812]  INFO -- packager-Windows2012:     ------------------
I, [2015-05-27T14:48:54.599567 #13812]  INFO -- packager-Windows2012:     # Declared in C:/tmp/kitchen/cache/cookbooks/chef-client/recipes/task.rb:32:in `from_file'
I, [2015-05-27T14:48:54.599567 #13812]  INFO -- packager-Windows2012:     
I, [2015-05-27T14:48:54.599567 #13812]  INFO -- packager-Windows2012:     windows_task("\chef-client") do
I, [2015-05-27T14:48:54.599567 #13812]  INFO -- packager-Windows2012:       action :create
I, [2015-05-27T14:48:54.599567 #13812]  INFO -- packager-Windows2012:       retries 0
I, [2015-05-27T14:48:54.599567 #13812]  INFO -- packager-Windows2012:       retry_delay 2
I, [2015-05-27T14:48:54.599567 #13812]  INFO -- packager-Windows2012:       default_guard_interpreter :default
I, [2015-05-27T14:48:54.600067 #13812]  INFO -- packager-Windows2012:       declared_type :windows_task
I, [2015-05-27T14:48:54.600067 #13812]  INFO -- packager-Windows2012:       cookbook_name "chef-client"
I, [2015-05-27T14:48:54.600067 #13812]  INFO -- packager-Windows2012:       recipe_name "task"
I, [2015-05-27T14:48:54.600067 #13812]  INFO -- packager-Windows2012:       run_level :highest
I, [2015-05-27T14:48:54.600067 #13812]  INFO -- packager-Windows2012:       command "cmd /c ' C:/opscode/chef/bin/chef-client   -L C:/chef/log/client.log   -c C:/chef/client.rb -s 300 > NUL 2>&1'"
I, [2015-05-27T14:48:54.600067 #13812]  INFO -- packager-Windows2012:       user "SYSTEM"
I, [2015-05-27T14:48:54.600067 #13812]  INFO -- packager-Windows2012:       frequency :onstart
I, [2015-05-27T14:48:54.600067 #13812]  INFO -- packager-Windows2012:       frequency_modifier 30
I, [2015-05-27T14:48:54.600067 #13812]  INFO -- packager-Windows2012:       task_name "\\chef-client"
I, [2015-05-27T14:48:54.600568 #13812]  INFO -- packager-Windows2012:     end
I, [2015-05-27T14:48:54.600568 #13812]  INFO -- packager-Windows2012:     
I, [2015-05-27T14:48:54.681084 #13812]  INFO -- packager-Windows2012: 
I, [2015-05-27T14:48:54.681584 #13812]  INFO -- packager-Windows2012: Running handlers:
I, [2015-05-27T14:48:54.682084 #13812]  INFO -- packager-Windows2012: [2015-05-27T14:48:54+01:00] ERROR: Running exception handlers
I, [2015-05-27T14:48:54.682084 #13812]  INFO -- packager-Windows2012: Running handlers complete
I, [2015-05-27T14:48:54.682084 #13812]  INFO -- packager-Windows2012: [2015-05-27T14:48:54+01:00] ERROR: Exception handlers complete
I, [2015-05-27T14:48:54.692586 #13812]  INFO -- packager-Windows2012: [2015-05-27T14:48:54+01:00] FATAL: Stacktrace dumped to C:/tmp/kitchen/cache/chef-stacktrace.out
I, [2015-05-27T14:48:54.697087 #13812]  INFO -- packager-Windows2012: Chef Client failed. 13 resources updated in 105.812473 seconds
I, [2015-05-27T14:48:54.700087 #13812]  INFO -- packager-Windows2012: [2015-05-27T14:48:54+01:00] FATAL: NoMethodError: windows_task[\chef-client] (chef-client::task line 32) had an error: NoMethodError: undefined method `password=' for Chef::Resource::WindowsTask
E, [2015-05-27T14:48:55.564260 #13812] ERROR -- packager-Windows2012: Converge failed on instance <packager-Windows2012>.
E, [2015-05-27T14:48:55.564260 #13812] ERROR -- packager-Windows2012: ------Exception-------
E, [2015-05-27T14:48:55.564760 #13812] ERROR -- packager-Windows2012: Class: Kitchen::Transport::TransportFailed
E, [2015-05-27T14:48:55.564760 #13812] ERROR -- packager-Windows2012: Message: Transport WinRM exited (1) using shell [powershell] for command: [&$env:systemdrive\opscode\chef/bin\chef-client.bat --local-mode --config /tmp/kitchen/client.rb --log_level auto --force-formatter --no-color  --chef-zero-port 8889 --json-attributes /tmp/kitchen/dna.json ]
REMOTE ERROR:

E, [2015-05-27T14:48:55.564760 #13812] ERROR -- packager-Windows2012: ------Backtrace-------
E, [2015-05-27T14:48:55.564760 #13812] ERROR -- packager-Windows2012: C:/Users/ebrahim.moshaya/.chefdk/gem/ruby/2.0.0/bundler/gems/test-kitchen-351f864f0e29/lib/kitchen/transport/winrm.rb:56:in `execute'
E, [2015-05-27T14:48:55.564760 #13812] ERROR -- packager-Windows2012: C:/Users/ebrahim.moshaya/.chefdk/gem/ruby/2.0.0/bundler/gems/test-kitchen-351f864f0e29/lib/kitchen/driver/base.rb:73:in `block in converge'
E, [2015-05-27T14:48:55.564760 #13812] ERROR -- packager-Windows2012: C:/Users/ebrahim.moshaya/.chefdk/gem/ruby/2.0.0/bundler/gems/test-kitchen-351f864f0e29/lib/kitchen/transport/base.rb:73:in `connection'
E, [2015-05-27T14:48:55.564760 #13812] ERROR -- packager-Windows2012: C:/Users/ebrahim.moshaya/.chefdk/gem/ruby/2.0.0/bundler/gems/test-kitchen-351f864f0e29/lib/kitchen/driver/base.rb:67:in `converge'
E, [2015-05-27T14:48:55.565260 #13812] ERROR -- packager-Windows2012: C:/Users/ebrahim.moshaya/.chefdk/gem/ruby/2.0.0/bundler/gems/kitchen-vagrant-00255c6879a0/lib/kitchen/driver/vagrant.rb:88:in `converge'
E, [2015-05-27T14:48:55.565260 #13812] ERROR -- packager-Windows2012: C:/Users/ebrahim.moshaya/.chefdk/gem/ruby/2.0.0/bundler/gems/test-kitchen-351f864f0e29/lib/kitchen/instance.rb:378:in `public_send'
E, [2015-05-27T14:48:55.565260 #13812] ERROR -- packager-Windows2012: C:/Users/ebrahim.moshaya/.chefdk/gem/ruby/2.0.0/bundler/gems/test-kitchen-351f864f0e29/lib/kitchen/instance.rb:378:in `block in perform_action'
E, [2015-05-27T14:48:55.565260 #13812] ERROR -- packager-Windows2012: C:/Users/ebrahim.moshaya/.chefdk/gem/ruby/2.0.0/bundler/gems/test-kitchen-351f864f0e29/lib/kitchen/instance.rb:442:in `call'
E, [2015-05-27T14:48:55.565260 #13812] ERROR -- packager-Windows2012: C:/Users/ebrahim.moshaya/.chefdk/gem/ruby/2.0.0/bundler/gems/test-kitchen-351f864f0e29/lib/kitchen/instance.rb:442:in `synchronize_or_call'
E, [2015-05-27T14:48:55.565260 #13812] ERROR -- packager-Windows2012: C:/Users/ebrahim.moshaya/.chefdk/gem/ruby/2.0.0/bundler/gems/test-kitchen-351f864f0e29/lib/kitchen/instance.rb:407:in `block in action'
E, [2015-05-27T14:48:55.565761 #13812] ERROR -- packager-Windows2012: C:/opscode/chefdk/embedded/lib/ruby/2.0.0/benchmark.rb:281:in `measure'
E, [2015-05-27T14:48:55.565761 #13812] ERROR -- packager-Windows2012: C:/Users/ebrahim.moshaya/.chefdk/gem/ruby/2.0.0/bundler/gems/test-kitchen-351f864f0e29/lib/kitchen/instance.rb:406:in `action'
E, [2015-05-27T14:48:55.565761 #13812] ERROR -- packager-Windows2012: C:/Users/ebrahim.moshaya/.chefdk/gem/ruby/2.0.0/bundler/gems/test-kitchen-351f864f0e29/lib/kitchen/instance.rb:378:in `perform_action'
E, [2015-05-27T14:48:55.565761 #13812] ERROR -- packager-Windows2012: C:/Users/ebrahim.moshaya/.chefdk/gem/ruby/2.0.0/bundler/gems/test-kitchen-351f864f0e29/lib/kitchen/instance.rb:338:in `converge_action'
E, [2015-05-27T14:48:55.565761 #13812] ERROR -- packager-Windows2012: C:/Users/ebrahim.moshaya/.chefdk/gem/ruby/2.0.0/bundler/gems/test-kitchen-351f864f0e29/lib/kitchen/instance.rb:318:in `block in transition_to'
E, [2015-05-27T14:48:55.565761 #13812] ERROR -- packager-Windows2012: C:/Users/ebrahim.moshaya/.chefdk/gem/ruby/2.0.0/bundler/gems/test-kitchen-351f864f0e29/lib/kitchen/instance.rb:317:in `each'
E, [2015-05-27T14:48:55.565761 #13812] ERROR -- packager-Windows2012: C:/Users/ebrahim.moshaya/.chefdk/gem/ruby/2.0.0/bundler/gems/test-kitchen-351f864f0e29/lib/kitchen/instance.rb:317:in `transition_to'
E, [2015-05-27T14:48:55.566261 #13812] ERROR -- packager-Windows2012: C:/Users/ebrahim.moshaya/.chefdk/gem/ruby/2.0.0/bundler/gems/test-kitchen-351f864f0e29/lib/kitchen/instance.rb:138:in `converge'
E, [2015-05-27T14:48:55.566261 #13812] ERROR -- packager-Windows2012: C:/Users/ebrahim.moshaya/.chefdk/gem/ruby/2.0.0/bundler/gems/test-kitchen-351f864f0e29/lib/kitchen/command.rb:176:in `public_send'
E, [2015-05-27T14:48:55.566261 #13812] ERROR -- packager-Windows2012: C:/Users/ebrahim.moshaya/.chefdk/gem/ruby/2.0.0/bundler/gems/test-kitchen-351f864f0e29/lib/kitchen/command.rb:176:in `block (2 levels) in run_action'
E, [2015-05-27T14:48:55.566261 #13812] ERROR -- packager-Windows2012: C:/Users/ebrahim.moshaya/.chefdk/gem/ruby/2.0.0/gems/logging-1.8.2/lib/logging/diagnostic_context.rb:323:in `call'
E, [2015-05-27T14:48:55.566261 #13812] ERROR -- packager-Windows2012: C:/Users/ebrahim.moshaya/.chefdk/gem/ruby/2.0.0/gems/logging-1.8.2/lib/logging/diagnostic_context.rb:323:in `block in create_with_logging_context'
E, [2015-05-27T14:48:55.566261 #13812] ERROR -- packager-Windows2012: ----------------------

**Comment by jhauf-nativex** [comment]
+1 Having the same issue

**Comment by jdmundrawala** [comment]
C:/tmp/kitchen/cache/chef-stacktrace.out is the file I want. It will be on the vm

**Comment by ebrahim-moshaya** [comment]
sorry about that!

Generated at 2015-05-27 14:48:54 +0100
NoMethodError: windows_task[\chef-client] (chef-client::task line 32) had an error: NoMethodError: undefined method `password=' for Chef::Resource::WindowsTask
C:/opscode/chef/embedded/apps/chef/lib/chef/resource.rb:959:in `method_missing'
C:/tmp/kitchen/cache/cookbooks/windows/providers/task.rb:212:in `validate_user_and_password'
C:/tmp/kitchen/cache/cookbooks/windows/providers/task.rb:30:in `block in class_from_file'
C:/opscode/chef/embedded/apps/chef/lib/chef/provider/lwrp_base.rb:60:in `instance_eval'
C:/opscode/chef/embedded/apps/chef/lib/chef/provider/lwrp_base.rb:60:in `recipe_eval_with_update_check'
C:/opscode/chef/embedded/apps/chef/lib/chef/provider/lwrp_base.rb:45:in `block in action'
C:/opscode/chef/embedded/apps/chef/lib/chef/provider.rb:134:in `run_action'
C:/opscode/chef/embedded/apps/chef/lib/chef/resource.rb:562:in `run_action'
C:/opscode/chef/embedded/apps/chef/lib/chef/runner.rb:49:in `run_action'
C:/opscode/chef/embedded/apps/chef/lib/chef/runner.rb:81:in `block (2 levels) in converge'
C:/opscode/chef/embedded/apps/chef/lib/chef/runner.rb:81:in `each'
C:/opscode/chef/embedded/apps/chef/lib/chef/runner.rb:81:in `block in converge'
C:/opscode/chef/embedded/apps/chef/lib/chef/resource_collection/resource_list.rb:83:in `block in execute_each_resource'
C:/opscode/chef/embedded/apps/chef/lib/chef/resource_collection/stepable_iterator.rb:116:in `call'
C:/opscode/chef/embedded/apps/chef/lib/chef/resource_collection/stepable_iterator.rb:116:in `call_iterator_block'
C:/opscode/chef/embedded/apps/chef/lib/chef/resource_collection/stepable_iterator.rb:85:in `step'
C:/opscode/chef/embedded/apps/chef/lib/chef/resource_collection/stepable_iterator.rb:104:in `iterate'
C:/opscode/chef/embedded/apps/chef/lib/chef/resource_collection/stepable_iterator.rb:55:in `each_with_index'
C:/opscode/chef/embedded/apps/chef/lib/chef/resource_collection/resource_list.rb:81:in `execute_each_resource'
C:/opscode/chef/embedded/apps/chef/lib/chef/runner.rb:80:in `converge'
C:/opscode/chef/embedded/apps/chef/lib/chef/client.rb:339:in `block in converge'
C:/opscode/chef/embedded/apps/chef/lib/chef/client.rb:334:in `catch'
C:/opscode/chef/embedded/apps/chef/lib/chef/client.rb:334:in `converge'
C:/opscode/chef/embedded/apps/chef/lib/chef/client.rb:353:in `converge_and_save'
C:/opscode/chef/embedded/apps/chef/lib/chef/client.rb:457:in `run'
C:/opscode/chef/embedded/apps/chef/lib/chef/application.rb:253:in `run_with_graceful_exit_option'
C:/opscode/chef/embedded/apps/chef/lib/chef/application.rb:230:in `block in run_chef_client'
C:/opscode/chef/embedded/apps/chef/lib/chef/local_mode.rb:39:in `with_server_connectivity'
C:/opscode/chef/embedded/apps/chef/lib/chef/application.rb:213:in `run_chef_client'
C:/opscode/chef/embedded/apps/chef/lib/chef/application/client.rb:402:in `block in interval_run_chef_client'
C:/opscode/chef/embedded/apps/chef/lib/chef/application/client.rb:392:in `loop'
C:/opscode/chef/embedded/apps/chef/lib/chef/application/client.rb:392:in `interval_run_chef_client'
C:/opscode/chef/embedded/apps/chef/lib/chef/application/client.rb:382:in `run_application'
C:/opscode/chef/embedded/apps/chef/lib/chef/application.rb:60:in `run'
C:/opscode/chef/embedded/apps/chef/bin/chef-client:26:in `<top (required)>'
C:/opscode/chef/bin/chef-client:63:in `load'
C:/opscode/chef/bin/chef-client:63:in `<main>'

**Comment by jhauf-nativex** [comment]
If it helps:

Generated at 2015-05-27 09:03:19 -0500
Chef::Exceptions::ValidationFailed: Option frequency_modifier must be a kind of Integer!  You passed "THIRD".
C:/opscode/chef/embedded/apps/chef/lib/chef/mixin/params_validate.rb:157:in `_pv_kind_of'
C:/opscode/chef/embedded/apps/chef/lib/chef/mixin/params_validate.rb:70:in `block (2 levels) in validate'
C:/opscode/chef/embedded/apps/chef/lib/chef/mixin/params_validate.rb:67:in `each'
C:/opscode/chef/embedded/apps/chef/lib/chef/mixin/params_validate.rb:67:in `block in validate'
C:/opscode/chef/embedded/apps/chef/lib/chef/mixin/params_validate.rb:57:in `each'
C:/opscode/chef/embedded/apps/chef/lib/chef/mixin/params_validate.rb:57:in `validate'
C:/opscode/chef/embedded/apps/chef/lib/chef/mixin/params_validate.rb:97:in `set_or_return'
C:/opscode/chef/embedded/apps/chef/lib/chef/resource/lwrp_base.rb:77:in `block in attribute'
c:/chef/cache/cookbooks/autopatch-nativex/recipes/windows.rb:21:in `block in from_file'
C:/opscode/chef/embedded/apps/chef/lib/chef/resource_builder.rb:70:in `instance_eval'
C:/opscode/chef/embedded/apps/chef/lib/chef/resource_builder.rb:70:in `build'
C:/opscode/chef/embedded/apps/chef/lib/chef/dsl/recipe.rb:144:in `build_resource'
C:/opscode/chef/embedded/apps/chef/lib/chef/dsl/recipe.rb:105:in `declare_resource'
C:/opscode/chef/embedded/apps/chef/lib/chef/dsl/recipe.rb:44:in `method_missing'
c:/chef/cache/cookbooks/autopatch-nativex/recipes/windows.rb:18:in `from_file'
C:/opscode/chef/embedded/apps/chef/lib/chef/mixin/from_file.rb:30:in `instance_eval'
C:/opscode/chef/embedded/apps/chef/lib/chef/mixin/from_file.rb:30:in `from_file'
C:/opscode/chef/embedded/apps/chef/lib/chef/cookbook_version.rb:218:in `load_recipe'
C:/opscode/chef/embedded/apps/chef/lib/chef/run_context.rb:173:in `load_recipe'
C:/opscode/chef/embedded/apps/chef/lib/chef/run_context.rb:142:in `block in include_recipe'
C:/opscode/chef/embedded/apps/chef/lib/chef/run_context.rb:141:in `each'
C:/opscode/chef/embedded/apps/chef/lib/chef/run_context.rb:141:in `include_recipe'
C:/opscode/chef/embedded/apps/chef/lib/chef/dsl/include_recipe.rb:26:in `include_recipe'
c:/chef/cache/cookbooks/autopatch-nativex/recipes/default.rb:16:in `from_file'
C:/opscode/chef/embedded/apps/chef/lib/chef/mixin/from_file.rb:30:in `instance_eval'
C:/opscode/chef/embedded/apps/chef/lib/chef/mixin/from_file.rb:30:in `from_file'
C:/opscode/chef/embedded/apps/chef/lib/chef/cookbook_version.rb:218:in `load_recipe'
C:/opscode/chef/embedded/apps/chef/lib/chef/run_context.rb:173:in `load_recipe'
C:/opscode/chef/embedded/apps/chef/lib/chef/run_context.rb:142:in `block in include_recipe'
C:/opscode/chef/embedded/apps/chef/lib/chef/run_context.rb:141:in `each'
C:/opscode/chef/embedded/apps/chef/lib/chef/run_context.rb:141:in `include_recipe'
C:/opscode/chef/embedded/apps/chef/lib/chef/dsl/include_recipe.rb:26:in `include_recipe'
c:/chef/cache/cookbooks/role-win-onpremise-base-nativex/recipes/default.rb:12:in `from_file'
C:/opscode/chef/embedded/apps/chef/lib/chef/mixin/from_file.rb:30:in `instance_eval'
C:/opscode/chef/embedded/apps/chef/lib/chef/mixin/from_file.rb:30:in `from_file'
C:/opscode/chef/embedded/apps/chef/lib/chef/cookbook_version.rb:218:in `load_recipe'
C:/opscode/chef/embedded/apps/chef/lib/chef/run_context.rb:173:in `load_recipe'
C:/opscode/chef/embedded/apps/chef/lib/chef/run_context/cookbook_compiler.rb:140:in `block in compile_recipes'
C:/opscode/chef/embedded/apps/chef/lib/chef/run_context/cookbook_compiler.rb:138:in `each'
C:/opscode/chef/embedded/apps/chef/lib/chef/run_context/cookbook_compiler.rb:138:in `compile_recipes'
C:/opscode/chef/embedded/apps/chef/lib/chef/run_context/cookbook_compiler.rb:75:in `compile'
C:/opscode/chef/embedded/apps/chef/lib/chef/run_context.rb:96:in `load'
C:/opscode/chef/embedded/apps/chef/lib/chef/policy_builder/expand_node_object.rb:73:in `setup_run_context'
C:/opscode/chef/embedded/apps/chef/lib/chef/client.rb:249:in `setup_run_context'
C:/opscode/chef/embedded/apps/chef/lib/chef/client.rb:445:in `run'
C:/opscode/chef/embedded/apps/chef/lib/chef/application.rb:253:in `run_with_graceful_exit_option'
C:/opscode/chef/embedded/apps/chef/lib/chef/application.rb:230:in `block in run_chef_client'
C:/opscode/chef/embedded/apps/chef/lib/chef/local_mode.rb:38:in `with_server_connectivity'
C:/opscode/chef/embedded/apps/chef/lib/chef/application.rb:213:in `run_chef_client'
C:/opscode/chef/embedded/apps/chef/lib/chef/application/client.rb:365:in `run_application'
C:/opscode/chef/embedded/apps/chef/lib/chef/application.rb:60:in `run'
C:/opscode/chef/embedded/apps/chef/bin/chef-client:26:in `<top (required)>'
C:/opscode/chef/bin/chef-client:64:in `load'
C:/opscode/chef/bin/chef-client:64:in `<main>'

Note: This was working prior to the update. I can get a few other errors if you need.

**Comment by jdmundrawala** [comment]
@jhauf-nativex I think you have a different problem. Can you please open another issue.

**Comment by jdmundrawala** [comment]
@ebrahim-moshaya can you point your windows cookbook at branch `jdm/219` and see if it fixes your issue?

**Comment by ebrahim-moshaya** [comment]
@jdmundrawala Thanks I can confirm jdm/219 fixes this issue

**Comment by btm** [comment]
https://github.com/opscode-cookbooks/windows/pull/220
