### ISSUE TITLE
Version on supermarket is different than version on github.

### ISSUE THREAD

**Issue by spuder** [opscode-cookbooks/windows#240]
Has the version number on github been blind rev-ed? 

Version 1.37.0 on github has a lwrp 'windows_http_acl'
Version 1.37.0 on the supermarket doesn't have 'windows_http_acl'

I'm not sure how this is possible, but it is bad.

**Comment by jaym** [comment]
*sigh*

**Comment by jaym** [comment]
I don't think this is correct: https://github.com/opscode-cookbooks/windows/tree/v1.37.0/resources
1.37.0 does not have windoes_http_acl

**Comment by spuder** [comment]
So as I look at this further, I see that the master branch is acting as a development branch. The readme in HEAD is newer than what was released with 1.37.0. The windows_http_acl feature was just added in this commit on may 26th. 83d20de5f42665ae1acc86491b9688fba179a057

Further confusion was added because I"m new to chef, and didn't realize that putting the git repo in my berksfile, caused berks to pull from github HEAD. Even though `knife cookbook show windows`  says that I have cookbook version 1.37.0, thats a lie.  I actually have 1.37.0 + everything committed to master since may 14th. 

I'll have to be more careful about what I put in my berks file. One way that github could have saved me from this mistake, is if the git repo used the [git-flow branching model](https://www.atlassian.com/git/tutorials/comparing-workflows/feature-branch-workflow), and only merged from dev to master when the version is bumped, then it would have saved me (and my chef noob coworkers) from making the mistake of accidentally using a non versioned cookbook.

**Comment by jaym** [comment]
yea, we should bump the version after a release to make it clear you're on a dev version... sorry for the confusion
