### ISSUE TITLE
windows_package should be consistent with Chef::Resource::WindowsPackage

### ISSUE THREAD

**Issue by dcode** [opscode-cookbooks/windows#269]
Per the [Chef docs][https://docs.chef.io/resource_windows_package.html], the windows_package resource uses "returns" to check success or failure of return codes. However, Chef::Resource::WindowsCookbookPackage overrides this cookbook and uses "status_codes". Took a bit of digging around to find this discrepancy. This should ideally use the same interface as the overridden resource, but at a minimum be highlighted as a difference.

**Comment by jaym** [comment]
That's a different `windows_package` resource. Core Chef has it's own which is different from the one in the windows cookbook

**Comment by dcode** [comment]
Yes, I know it's a different `windows_package` resource, but the windows cookbook resource overrides the Core Chef resource. Why not implement the same interface (methods)? The function of the resource is the same, and it _mostly_ has the same properties.
